buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Cập nhật lên bản plugin mới nhất để tương thích Gradle 9
        classpath 'com.android.tools.build:gradle:8.2.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
